# Generated by Django 4.0.5 on 2022-08-29 23:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0010_profile_delete_coder'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='code_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
    ]
